// This work is licensed under a Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © LuxAlgo

//@version = 4
study(title="SnR Breaks FixedTF", shorttitle = "SnR Breaks FixedTF", overlay = true, max_bars_back=1000)

// --- Fixed Timeframe Input ---
fixedTF = input(title="Fixed Timeframe", type=input.resolution, defval="240")

// Get security data
fixedHigh   = security(syminfo.tickerid, fixedTF, high)
fixedLow    = security(syminfo.tickerid, fixedTF, low)
fixedVolume = security(syminfo.tickerid, fixedTF, volume)

// Inputs
toggleBreaks  = input(true, title="Show Breaks")
leftBars      = input(15, title="Left Bars")
rightBars     = input(15, title="Right Bars")
volumeThresh  = input(20, title="Volume Threshold")

// Support & Resistance pivots on fixed timeframe
highUsePivot = fixnan(pivothigh(fixedHigh, leftBars, rightBars)[1])
lowUsePivot  = fixnan(pivotlow(fixedLow, leftBars, rightBars)[1])

// Plot
r1 = plot(highUsePivot, color=change(highUsePivot) ? na : color.rgb(219, 13, 185), linewidth=2, offset=-(rightBars+1), title="Resistance")
s1 = plot(lowUsePivot, color=change(lowUsePivot) ? na : #0eebe0, linewidth=2, offset=-(rightBars+1), title="Support")

// Volume % oscillator
short = ema(fixedVolume, 5)
long  = ema(fixedVolume, 10)
osc   = 100 * (short - long) / long
